---
branches:
  only:
    - master
language: ruby
bundler_args: --without development
script: 'bundle exec rake validate && bundle exec rake lint && SPEC_OPTS="--format documentation" bundle exec rake spec'
rvm:
  - 2.0.0
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.7.0"
  global:
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.1.0"
notifications:
  email: false
